### ISSUE TITLE
cuda and torch version used in AuroraCap

### ISSUE THREAD

**Issue by Fr0zenCrane** [rese1f/aurora#7]
Hi, thank you for your excellent work, and congratulations for your success on ICLR!

I’ve been trying to reproduce the results from your paper, but the performance I’ve obtained is significantly lower than what is reported. For instance, the llava-ov-7B on VDC-Detailed are 29.03/2.02, compared to 41.20/2.13 in your paper.

Since the evaluation setup in lmms-eval doesn’t seem to allow for any changes or modifications, and based on discussions in some of the issues within the lmms-eval project, I suspect this performance drop might be due to differences in the CUDA or PyTorch versions.

Would you mind sharing the specific versions of CUDA and PyTorch that you used? I’d greatly appreciate your help.

Below is my evaluation scripts:

```
export HF_HOME="path_to_the_local_datasets"
export API_TYPE="openai"
export OPENAI_API_URL="my_openai_api_url"
export OPENAI_API_KEY="my_openai_api_key"

python3 -m accelerate.commands.launch \
    --num_processes=8 \
    -m lmms_eval \
    --model llava_onevision \
    --model_args pretrained="lmms-lab/llava-onevision-qwen2-7b-ov",conv_template="qwen_1_5",model_name="llava_qwen" \
    --tasks detailed_test \
    --batch_size 1 \
    --log_samples \
    --log_samples_suffix llava_ov_video_dc \
    --output_path ./logs/llava_ov_video_dc \
    --verbosity=DEBUG 
```

**Comment by Espere-1119-Song** [comment]
Thanks for your question! We found that results produced by GPT-4o can be quite unstable. To ensure a fair comparison, we tested multiple open-source LLMs and found that LLaMA 3.1-8B consistently reproduces the results reported in our paper. Additionally, we have updated the evaluation assistant code in lmms-eval to use LLaMA 3.1-8B for evaluation. Feel free to give it a try, and let us know if you encounter any issues!

**Comment by Fr0zenCrane** [comment]
Thank you for your response and clarification. Through your response, I think that not only I, but also others interested in VDCScore, would benefit significantly from having instructions on how to perform VDCScore evaluation using LLaMA3.1. The default behavior of the code on lmms-eval uses gpt-4o-mini for evaluation, and I couldn't find any instructions for using LLaMA3.1 in either lmms-eval or this repository. 

Could you please provide one, those who interested in VDCScore will greatly appreciate this!

**Comment by Espere-1119-Song** [comment]
Hi, we updated the code in the lmms-eval repository last month, so please try performing a git pull to get the latest version. Thank you for your reminder! We will also update the evaluation code and provide clearer instructions in this repository shortly to assist everyone interested in VDCScore.

**Comment by Fr0zenCrane** [comment]
Hi, sorry for the late response. You were absolutely right—the code I initially cloned was not the latest version. After performing a git pull, I am pleased to share that my reproduced results are now very close to those reported in your paper, the score is almost the same as yours, and the difference of the acc is less than 1.0. I really appreciate you for your clarity of your code, which surely save a lot of my time!

That said, I noticed a small issue in the code that occasionally triggers the following error
`Error for video name: xxxxxx: string indices must be integers`

Upon investigating, I found that this issue arises because, although the response from LLaMA 3.1 is mostly correct, it sometimes returns a string like:
`" "{'pred': 'no', 'score': 1}" "`
Here, there are two levels of quotation marks ("), which causes the value of ast.literal_eval(response) in function gpt_match, is not always a dict, it might also be as a str. To solve this problem, we can add a type examiniation on `response_dict`, then we give it a default value like` {'pred':'no', 'score':0}`  or `response_dict = ast.literal_eval(response_dict)` to get the right answer.

To align more closely with your settings, would you recommend fixing this issue , or should this behavior be preserved as is?

**Comment by Fr0zenCrane** [comment]
OK, thanks again for your help, I will close this issue since all my questions are answered, wish you a good day!
